### ISSUE TITLE
Umstellung auf Maven Build

### ISSUE THREAD

**Issue by aubelix** [reitmeier/liferayplugins#4]
Wir werden den Maven Build von Liferay verwenden.
Dann müssen wir den Plugins Folder nicht mehr einchecken.

Ich werde das dieses Wochenende ändern, bitte alle Änderungen einchecken.

**Comment by clausprivat** [comment]
OK ich hab aktuell nichts offen. Bitte SAG uns dann was wir lokal in der
entwicklungsumgebung umstellen müssen... lg
Am 03.07.2015 21:13 schrieb "aubelix" notifications@github.com:
