### ISSUE TITLE
#9 not all vocabularies are listed

### ISSUE THREAD

**Issue by reitmeier** [reitmeier/liferayplugins#9]
1.)Added new vocabulary
2.)Edit Task and search for this new vocabulary but it was not found

**Comment by bsch92** [comment]
currently filtering for groupId so that vocabularies with different groupId are not displayed to prevent access issues, can change this behaviour if needed

**Comment by clausprivat** [comment]
Do you mean the sites groupid?  it makes sense to limit selection to global
plus the currently selected site.
Am 15.07.2015 16:32 schrieb "b-schmitzer" notifications@github.com:
